name: cel
description: This project parses and evaluates Common Expression Language (CEL) programs against some inputs.
version: 0.5.3
repository: https://github.com/atn832/cel-dart
homepage: https://www.wafrat.com
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  antlr4: ^4.11.1
  collection: ^1.16.0
  equatable: ^2.0.5
  protobuf: ^5.0.0
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
  protoc_plugin: ^23.0.0

dependency_overrides:
  protobuf:
    path: ../protobuf.dart/protobuf
  protoc_plugin:
    git:
      url: https://github.com/titanous/protobuf.dart
      ref: efb8b3d70edf6619a4873fd9785e724c91720f09
      path: protoc_plugin
